### ISSUE TITLE
Allow uri Source propType

### ISSUE THREAD

**Issue by b8ne** [Osedea/react-native-interactive-avatar#3]
Currently if I pre-supply a uri to the Avatar source I get an invalid proptype warning.

**Comment by adrienthiery** [comment]
Hi @b8ne,

Thanks for the feedback.

Do you mean if you supply an object with a URI key? (Like `{ uri: "https://myuri.com/my image.png" }`)

For faster use, the Avatar has been defined as taking URIs by default as source (so just the URI, no need of an object).

If you want to have the behaviour of the Image component, you need to add the `isRequire` attribute.

**Comment by b8ne** [comment]
No worries @adrienthiery 
Great library btw, exactly what I was about to start building myself until I found this.

So yeah im using an external url attached to a user model, and need to show a default if the user model is null.
Currently I have 
```
<Avatar
    source={this.props.user.avatar != null ? {uri: this.props.user.avatar} : require('../../assets/images/user_plus.png')}
    size={'default'}
    style={styles.avatar}
    isRequire={true}
    interactive={this.props.isEditing}
    onChange={this._handleImageChange}
/>
```
but am getting the failed prop type warning.  
Is there currently a better way of doing this that you can think of?

Edit: I can see how `getAppropriateSource` should convert to a `uri` however for some reason its not.
I just updated propTypes to be 
```
source: React.PropTypes.oneOfType([
            Image.propTypes.source,
            React.PropTypes.string,
            React.PropTypes.number, // if require
        ]),
``` 
and its working fine.

**Comment by adrienthiery** [comment]
Hi @b8ne,

I guess you could use the `placeholder` prop to set your `require('../../assets/images/user_plus.png')` image, right ?

and then just call `Avatar` with:
```
<Avatar
    source={this.props.user.avatar}
    placeholder={require('../../assets/images/user_plus.png')}
    size={'default'}
    style={styles.avatar}
    interactive={this.props.isEditing}
    onChange={this._handleImageChange}
/>
```

The `placeholder` prop is the image that is displayed when the `source` prop is `null` or `undefined`.

Sorry, I realize that I forgot to document it 😱

**Comment by adrienthiery** [comment]
Maybe I should clarify the names of the attributes though, it feels unclear...

**Comment by adrienthiery** [comment]
Hi again @b8ne,

I upgraded `react-native-image-picker` and tried to make clearer attributes in v1.1.0, but now it requires react-native v0.40.

Check it out and tell me what you think ! 😄
